### ISSUE TITLE
Does not work on fresh Ubuntu 18.04

### ISSUE THREAD

**Issue by lstrz** [Ventto/xpub#4]
The output of `who` is, for example:
`user     :0           2018-08-22 10:54 (:0)`
without a `tty`, thus the `grep` on line 69 does not produce anything.

Upon closer examination, a bunch of other things fail too, even if correct values are hardcoded here and there. I know too little about the whole display setup to be of much help on my own.

**Comment by Ventto** [comment]
Hello @lstrz, 
Thanks for the feedback.

I will take a look sooner.
Until then, feel free to contribute !

**Comment by Ventto** [comment]
Duplicate with #3.
